version: '3'
services:
    
  db:
      image: mysql
      container_name: mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD="dali"
  web:
    image: apache_web
    build: ./webappp
    depends_on:
      - db
    container_name: apache
    restart: always
    ports:
      -  "8081:8080"